<?php 
/**
 * @file fctc.module
 *  Custom module for FCTC-ITP prototype.
 */

/**
 * Implements hook_menu().
 */
function fctc_menu() {
  $items = array();

  $items['fctc/tracing'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fctc_trace'),
    'title' => 'Tracing',
    'access arguments' => array('access content'),
    'file' => 'fctc.pages.inc',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'fctc',
  );
  $items['fctc/tracking/in-transit'] = array(
    'page callback' => 'fctc_tracking_in_transit',
    'title' => 'Tracking: Shipments in Transit',
    'access arguments' => array('access content'),
    'file' => 'fctc.pages.inc',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'fctc',
  );
  $items['fctc/tracking/routes-a'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fctc_track'),
    'title' => 'Tracking: Routes (A)',
    'access arguments' => array('access content'),
//    'file' => 'fctc.pages.inc',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'fctc',
  );
  $items['fctc/tracking/routes-b'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fctc_track'),
    'title' => 'Tracking: Routes (B)',
    'access arguments' => array('access content'),
//    'file' => 'fctc.pages.inc',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'fctc',
  );
  $items['fctc/tracking/query-tool-a'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fctc_track'),
    'title' => 'Tracking: Query Tool (A)',
    'access arguments' => array('access content'),
//    'file' => 'fctc.pages.inc',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'fctc',
  );
  $items['fctc/tracking/query-tool-b'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fctc_track'),
    'title' => 'Tracking: Query Tool (B)',
    'access arguments' => array('access content'),
//    'file' => 'fctc.pages.inc',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'fctc',
  );

  return $items; 
}

/**
 * Implements hook_theme().
 */
function fctc_theme() {
  return array(
    'fctc_tracking_in_transit' => array(
      'render element' => 'tracking data',
      'file' => 'fctc.pages.inc',
    ),  
    'fctc_tracking_sent_received' => array(
      'render element' => 'tracking data',
      'file' => 'fctc.pages.inc',
    ),  
    /*
    'fctc_tracing' => array(
      'render element' => 'tracing data',
      'file' => 'fctc.pages.inc',
    ),  
    // */
  );
}

/**
 * Implements hook_block_info().
 */
function fctc_block_info() {
  $blocks = array();
  $blocks['track form']['info'] = t('Tracking Form');
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function fctc_block_view($delta) {
  $block = array();

  switch ($delta) {
    case 'track form':
      $subject = '';
      $content = drupal_get_form('fctc_track');
    break;
  }
  $block['subject'] = $subject;
  $block['content'] = $content;
  
  return $block;
}

/**
 * @return $form
 *  Form array. 
 */
function fctc_track($form, &$form_state) {
  $data = fctc_get_data();

  $form['form header'] = array(
    '#type' => 'item',
    '#title' => t('Query Builder'),
    '#prefix' => '<h1>',
    '#suffix' => '</h1>',
  );    
  // From country.
  $form['origin'] = array(
    '#type' => 'select',
    '#title' => t('From Country'),
    '#options' => _fctc_track_options($data, 'origin'),
  );
  // To country.
  $form['destination'] = array(
    '#type' => 'select',
    '#title' => t('To Country'),
    '#options' => _fctc_track_options($data, 'destination'),
  );
  // Sender.
  $form['from'] = array(
    '#type' => 'select',
    '#title' => t('Sender'),
    '#options' => _fctc_track_options($data, 'from'),
  );
  // Recipient.
  $form['to'] = array(
    '#type' => 'select',
    '#title' => t('Recipient'),
    '#options' => _fctc_track_options($data, 'to'),
  );
  // Final destination.
  $form['final-destination'] = array(
    '#type' => 'select',
    '#title' => t('Final Destination'),
    '#options' => _fctc_track_options($data, 'final-destination'),
  );
  // Shipment description (sent/received).
  $form['description'] = array(
    '#type' => 'select',
    '#title' => t('Shipment Description'),
    '#options' => array(
      '' => t('<any>'),
      'sent' => t('sent'),
      'received' => t('received'),
    ),
  );
  // Date range.
  $form['before-date'] = array(
    '#type' => 'date_popup',
    '#title' => t('Before Date'),
    '#date_type' => DATE_UNIX,
    '#date_format' => 'd/m/Y',
  );
  $form['after-date'] = array(
    '#type' => 'date_popup',
    '#title' => t('After Date'),
    '#date_type' => DATE_UNIX,
    '#date_format' => 'd/m/Y',
  );
  // Shipment status (0 in transit, 1 received at final destination).
  $form['status'] = array(
    '#type' => 'select',
    '#title' => t('Shipment Status'),
    '#options' => array(
      '' => t('<all>'),
      '0' => t('In Transit'),
      '1' => t('Received at Final Destination'),
    ),
    //'#description' => t('A shipment that has been sent but not received at its '
      //                . 'final destiation is considered "in transit". Shipments '
        //              . 'that appear to be in transit indefinitely are suspicious.'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Run Query'),
  );

  // Show limited version of form on certan paths
  $form = fctc_track_form_element_access($form);

  // If form was rebuilt, display results from last query.
  if ($form_state['rebuild']) {
    $form = _fctc_track_results($form, $form_state['values'], $data);
  }
 
  return $form;
}

/**
 * Submit handler for fctc_track form.
 */
function fctc_track_submit(&$form, &$form_state) {
  $form_state['rebuild'] = TRUE;
}

//-----------------------------------------------------------------/
// Helper functions for processing data.                           /
//                                                                 /
// Note: These really only work for prototyping. These functions   /
// were easy and fast to write. But they won't scale.              /
//-----------------------------------------------------------------/
/**
 * Get all cached RDF data and store it in one big array.
 * Use this for processing data for track and trace examples.
 *
 * Make these values: 
 *   s, subject, e.g. http://localhost/countryx/node/20
 *   p, predicate, e.g. http://this.doesnt.really.get.checked.com/id
 *   o, object, e.g. 12345
 * Look like this:  
 *   $data['subject']['predicate'] = 'object';
 * 
 * @todo This is an RDF/SPARQL hack but it will make prototyping a lot faster
 * without getting bogged down in SPARQL syntax.
 * 
 * @return $data
 *  Array of sanitized shipment data in the following format:  
 *  $data['subject']['predicate'] = 'object';
 */
function fctc_get_data($short_predicate = TRUE) {
  // Get RDF data from SPARQL endpoint.
  $endpoint = url('sparql', array('absolute' => TRUE));
  $query = 'SELECT * WHERE {
            GRAPH ?g { ?s ?p ?o . }
           }';
  $sparql_results = sparql_request($query, $endpoint);

  // Convert SPARQL results to a friendlier array.
  $data = array();
  foreach ($sparql_results['result']['rows'] as $row) {
    // Sanitize data. 
    $subject = check_plain($row['s']);
    $predicate = check_plain($row['p']);
    $object = check_plain($row['o']);
    // Shorten predicate from this: http://this.doesnt.really.get.checked.com/id
    // to this: id.
    if ($short_predicate) {
      $position = strripos($predicate, '/') + 1;
      $predicate = substr($predicate, $position);
    }
    $data[$subject][$predicate] = $object;
  }

  return $data;
}

/**
 * @param $params
 *  Array. Parameters submitted via $form_state['values'] from a submitted 
 *  fctc_tracking form.
 * 
 * @param $delta
 *  String. What kind of results should be returned. Options:
 *  - count
 *  - list
 *
 * @return
 *  count, Integer
 *  list, data for table?
 */
function fctc_results($params, $data, $delta) {
  if (!$params) {
    return FALSE;  
  }

  $results = array();

  // Test query criteria against each shipment record. 
  foreach ($data as $uri => $shipment) {
    //dsm($shipment, 'shipment');
    // All values must match.
    foreach ($params as $param => $value) {
      if (isset($shipment[$param]) && $shipment[$param] == $value) {
        $match = TRUE;
      }
      // Handle cases where $shipment[$param] will not equal $value,
      // specifically: before date, after date, status.
      else if ($param == 'before-date' && isset($shipment['date']) && $shipment['date'] < fctc_datestamp($value)) {
        $match = TRUE;
      }
      else if ($param == 'after-date' && isset($shipment['date']) && $shipment['date'] > fctc_datestamp($value)) {
        $match = TRUE;
      }
      else if ($param == 'status' && isset($shipment['status']) && ((!$shipment['status'] && !$value) || ($shipment['status'] && $value)) ) {
        $match = TRUE;
      }
      else {
        $match = FALSE; 
        break;
      }
    }
    if ($match) {
      //dsm($shipment, 'shipment match');
      $results[$uri] = $shipment;
    }
  }

  if (!$results) {
    return FALSE;  
  }

  switch ($delta) {
    case 'count': 
      return count($results);
    break;

    case 'list':
      return fctc_list_results($results);
    break;
  }
}

/**
 * @param $results
 *  Array of shipments matching fctc_track form criteria.
 * 
 * @return
 *  $variables to be passed to theme_table().
 */
function fctc_list_results($results) {
  $variables = array();
  
  $header = array(
    array('data' => t('')),
    array('data' => t('Unique Identifier')),
    array('data' => t('From Country')),
    array('data' => t('To Country')), 
    array('data' => t('Description')),
    array('data' => t('Date')),
  );

  $order_by = array();
  foreach ($results as $uri => $value) {
    $order_by[$uri] = $value['date'];
  }
  asort($order_by);

  $rows = array();
  $i = 1;
  foreach ($order_by as $uri => $date) {
    $rows[] = array(
      $i,
      l($results[$uri]['id'], 'fctc/tracing/' . $results[$uri]['id']),
      $results[$uri]['origin'],
      $results[$uri]['destination'],
      $results[$uri]['description'],
      date('d-m-Y', $results[$uri]['date']),
    );
    $i++;
  }

  $variables['header'] = $header;
  $variables['rows'] = $rows;

  return $variables;
}

/**
 * @param $date
 *   String. yyyy-mm-dd.
 * 
 * @return
 *  Unix timestamp.
 */
function fctc_datestamp($date) {
  $parts = explode('-', $date);
  $yyyy = $parts[0];
  $mm = $parts[1];
  $dd = $parts[2];
  $datestamp = mktime(0, 0, 0, $mm, $dd, $yyyy);
 
  return $datestamp;
}

//------------------------------------------------------------------/
// Internal functions                                               /
//------------------------------------------------------------------/
/**
 * @param $data
 *  Array. Results of fctc_get_data().
 * 
 * @param $delta
 *  String. Which form element / RDF predicate we're generating options for.
 * 
 * @return
 *  Array. Select options. Recipients.
 */
function _fctc_track_options($data, $delta) {
  $options = array('' => t('<any>'));
  foreach ($data as $shipment) {
    if (isset($shipment[$delta])) {
      if (!empty($shipment[$delta]) && !in_array($shipment[$delta], $options)) {
        $value = check_plain($shipment[$delta]);
        $options[$value] = $value;
      }
    }
  }
  
  return $options;  
}

/**
 * To make fctc_track form re-usable as a block, use this function 
 * to check the path and return different results, depending on which
 * page the form is being used on.
 * 
 * Results are displayed along with rebuilt forms as form items.
 * 
 * @param $form
 *  Form array.
 * 
 * @param $values
 *  $values, $form_state['values'] from last form submission.
 * 
 * @param $data
 *  Array. @see fctc_get_data().
 * 
 * @return $form
 *  Form array.
 */
function _fctc_track_results($form, $values, $data) {
  // Display submitted query criteria above results as form items.
  $form['results header'] = array(
    '#type' => 'item',
    '#title' => t('Query Results'),
    '#prefix' => '<h1>',
    '#suffix' => '</h1>',
    '#weight' => -2,
  );
  $form['results'] = array(
    '#type' => 'fieldset',
    '#weight' => -1,
  );
  $params = array();
  foreach ($values as $key => $value) {
    // Only show values with titles, that is, form elements used as 
    // query parameters.
    if ((isset($form[$key]['#title']) && $value != NULL )
      || ($key == 'status' && strlen($value) > 0)) {
      // Hang onto these $params. This makes finding results easier later.
      $params[$key] = $value;
      // Get values for form item.
      $title = $form[$key]['#title'];
      $name = "item-$key";
      // Shipment Status values are boolean. The rest are human readable strings.
      if ($title == 'Shipment Status') {
        $value = $form[$key]['#options'][$value];
      }
      $title = $form[$key]['#title'] . ': ' . $value;
      // Add form item.
      $form['results'][$name] = array(
        '#type' => 'item',
        '#title' => $title,
      );    
    }
  }

  // Display different results based on path.
  switch (arg(2)) {
    // Path: fctc/tracking/routes-a
    case 'routes-a': 
      if ($count = fctc_results($params, $data, 'count')) {
      $form['results']['results'] = array(
        '#type' => 'item',
        '#title' => t('%count shipments match the criteria above.', 
                    array('%count' => $count)),
        '#prefix' => '<h2>',
        '#suffix' => '</h2>',
      );    
      }
      else {
        $form['results']['results'] = array(
          '#type' => 'item',
          '#title' => t('No results.'),
          '#prefix' => '<h2>',
          '#suffix' => '</h2>',
        );    
      }
    break;

    // Path: fctc/tracking/routes-b
    case 'routes-b': 
      if ($variables = fctc_results($params, $data, 'list')) {
        $form['results']['results header'] = array(
          '#type' => 'item',
          '#title' => t('The following shipments match the criteria above:'),
          '#prefix' => '<h2>',
          '#suffix' => '</h2>',
        );    
        $form['results']['results'] = array(
          '#type' => 'markup',
          '#markup' => theme('table', $variables),
        );    
      }
      else {
        $form['results']['results'] = array(
          '#type' => 'item',
          '#title' => t('No results.'),
          '#prefix' => '<h2>',
          '#suffix' => '</h2>',
        );    
      }
    break;

    // Path: fctc/tracking/query-tool-a
    case 'query-tool-a': 
      if ($count = fctc_results($params, $data, 'count')) {
      $form['results']['results'] = array(
        '#type' => 'item',
        '#title' => t('%count shipments match the criteria above.', 
                    array('%count' => $count)),
        '#prefix' => '<h2>',
        '#suffix' => '</h2>',
      );    
      }
      else {
        $form['results']['results'] = array(
          '#type' => 'item',
          '#title' => t('No results.'),
          '#prefix' => '<h2>',
          '#suffix' => '</h2>',
        );    
      }
    break;

    // Path: fctc/tracking/routes-b
    case 'query-tool-b': 
      if ($variables = fctc_results($params, $data, 'list')) {
        $form['results']['results header'] = array(
          '#type' => 'item',
          '#title' => t('The following shipments match the criteria above:'),
          '#prefix' => '<h2>',
          '#suffix' => '</h2>',
        );    
        $form['results']['results'] = array(
          '#type' => 'markup',
          '#markup' => theme('table', $variables),
        );    
      }
      else {
        $form['results']['results'] = array(
          '#type' => 'item',
          '#title' => t('No results.'),
          '#prefix' => '<h2>',
          '#suffix' => '</h2>',
        );    
      }
    break;
  }

  return $form;
}

/**
 * Show limited version of query builder form for certain paths.
 *
 * @param $form
 *  Form array.
 * 
 * @return $form
 *  Form array.
 */
function fctc_track_form_element_access($form) {
  switch (arg(2)) {
    case 'routes-a':
      $form['to']['#access'] = FALSE;
      $form['from']['#access'] = FALSE;
      $form['final-destination']['#access'] = FALSE;
      $form['description']['#access'] = FALSE;
      //$form['status']['#value'] = 0;
      //$form['status']['#access'] = FALSE;
    break;
    case 'routes-b':
      $form['to']['#access'] = FALSE;
      $form['from']['#access'] = FALSE;
      $form['final-destination']['#access'] = FALSE;
      $form['description']['#access'] = FALSE;
      //$form['status']['#value'] = 0;
      //$form['status']['#access'] = FALSE;
    break;
  }

  return $form;  
}
